spring:
  #禁用模板引擎缓存
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowershop?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123123
#    热部署生效
  devtools:
    restart:
      enabled: true
  mvc:
    date-format: yyyy-MM-dd
server:
  servlet:
    context-path: /crud
  port: 8080
debug: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml