package com.example.springboot03.pojo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oId
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oConsignee
     *
     * @mbg.generated
     */
    private String oconsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oPhone
     *
     * @mbg.generated
     */
    private String ophone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oAddress
     *
     * @mbg.generated
     */
    private String oaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oCreateTime
     *
     * @mbg.generated
     */
    private Date ocreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oState
     *
     * @mbg.generated
     */
    private Integer ostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oTotalPrice
     *
     * @mbg.generated
     */
    private Double ototalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oId
     *
     * @return the value of order.oId
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oId
     *
     * @param oid the value for order.oId
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oConsignee
     *
     * @return the value of order.oConsignee
     *
     * @mbg.generated
     */
    public String getOconsignee() {
        return oconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oConsignee
     *
     * @param oconsignee the value for order.oConsignee
     *
     * @mbg.generated
     */
    public void setOconsignee(String oconsignee) {
        this.oconsignee = oconsignee == null ? null : oconsignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oPhone
     *
     * @return the value of order.oPhone
     *
     * @mbg.generated
     */
    public String getOphone() {
        return ophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oPhone
     *
     * @param ophone the value for order.oPhone
     *
     * @mbg.generated
     */
    public void setOphone(String ophone) {
        this.ophone = ophone == null ? null : ophone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oAddress
     *
     * @return the value of order.oAddress
     *
     * @mbg.generated
     */
    public String getOaddress() {
        return oaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oAddress
     *
     * @param oaddress the value for order.oAddress
     *
     * @mbg.generated
     */
    public void setOaddress(String oaddress) {
        this.oaddress = oaddress == null ? null : oaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oCreateTime
     *
     * @return the value of order.oCreateTime
     *
     * @mbg.generated
     */
    public Date getOcreatetime() {
        return ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oCreateTime
     *
     * @param ocreatetime the value for order.oCreateTime
     *
     * @mbg.generated
     */
    public void setOcreatetime(Date ocreatetime) {
        this.ocreatetime = ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oState
     *
     * @return the value of order.oState
     *
     * @mbg.generated
     */
    public Integer getOstate() {
        return ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oState
     *
     * @param ostate the value for order.oState
     *
     * @mbg.generated
     */
    public void setOstate(Integer ostate) {
        this.ostate = ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oTotalPrice
     *
     * @return the value of order.oTotalPrice
     *
     * @mbg.generated
     */
    public Double getOtotalprice() {
        return ototalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oTotalPrice
     *
     * @param ototalprice the value for order.oTotalPrice
     *
     * @mbg.generated
     */
    public void setOtotalprice(Double ototalprice) {
        this.ototalprice = ototalprice;
    }
}