package com.example.springboot03.pojo;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_Id
     *
     * @mbg.generated
     */
    private Integer odId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_fId
     *
     * @mbg.generated
     */
    private Integer odFid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_fImgPath
     *
     * @mbg.generated
     */
    private String odFimgpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_fName
     *
     * @mbg.generated
     */
    private String odFname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_fPrice
     *
     * @mbg.generated
     */
    private Double odFprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_fCount
     *
     * @mbg.generated
     */
    private Integer odFcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_TotalPrice
     *
     * @mbg.generated
     */
    private Double odTotalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.od_oId
     *
     * @mbg.generated
     */
    private Integer odOid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_Id
     *
     * @return the value of order_details.od_Id
     *
     * @mbg.generated
     */
    public Integer getOdId() {
        return odId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_Id
     *
     * @param odId the value for order_details.od_Id
     *
     * @mbg.generated
     */
    public void setOdId(Integer odId) {
        this.odId = odId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_fId
     *
     * @return the value of order_details.od_fId
     *
     * @mbg.generated
     */
    public Integer getOdFid() {
        return odFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_fId
     *
     * @param odFid the value for order_details.od_fId
     *
     * @mbg.generated
     */
    public void setOdFid(Integer odFid) {
        this.odFid = odFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_fImgPath
     *
     * @return the value of order_details.od_fImgPath
     *
     * @mbg.generated
     */
    public String getOdFimgpath() {
        return odFimgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_fImgPath
     *
     * @param odFimgpath the value for order_details.od_fImgPath
     *
     * @mbg.generated
     */
    public void setOdFimgpath(String odFimgpath) {
        this.odFimgpath = odFimgpath == null ? null : odFimgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_fName
     *
     * @return the value of order_details.od_fName
     *
     * @mbg.generated
     */
    public String getOdFname() {
        return odFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_fName
     *
     * @param odFname the value for order_details.od_fName
     *
     * @mbg.generated
     */
    public void setOdFname(String odFname) {
        this.odFname = odFname == null ? null : odFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_fPrice
     *
     * @return the value of order_details.od_fPrice
     *
     * @mbg.generated
     */
    public Double getOdFprice() {
        return odFprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_fPrice
     *
     * @param odFprice the value for order_details.od_fPrice
     *
     * @mbg.generated
     */
    public void setOdFprice(Double odFprice) {
        this.odFprice = odFprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_fCount
     *
     * @return the value of order_details.od_fCount
     *
     * @mbg.generated
     */
    public Integer getOdFcount() {
        return odFcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_fCount
     *
     * @param odFcount the value for order_details.od_fCount
     *
     * @mbg.generated
     */
    public void setOdFcount(Integer odFcount) {
        this.odFcount = odFcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_TotalPrice
     *
     * @return the value of order_details.od_TotalPrice
     *
     * @mbg.generated
     */
    public Double getOdTotalprice() {
        return odTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_TotalPrice
     *
     * @param odTotalprice the value for order_details.od_TotalPrice
     *
     * @mbg.generated
     */
    public void setOdTotalprice(Double odTotalprice) {
        this.odTotalprice = odTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.od_oId
     *
     * @return the value of order_details.od_oId
     *
     * @mbg.generated
     */
    public Integer getOdOid() {
        return odOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.od_oId
     *
     * @param odOid the value for order_details.od_oId
     *
     * @mbg.generated
     */
    public void setOdOid(Integer odOid) {
        this.odOid = odOid;
    }
}