package com.example.springboot03.dao;

import com.example.springboot03.pojo.Flower;

import java.util.List;
public interface FlowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    int insert(Flower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    int insertSelective(Flower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    Flower selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Flower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Flower record);

    //获取flower集合
    List<Flower> getFlowers();
}