package com.example.springboot03.dao;

import com.example.springboot03.pojo.OrderDetails;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    OrderDetails selectByPrimaryKey(Integer odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderDetails record);
}